#Exceção personalizada, herda de Exception
class ConnectionError(Exception):
    pass
